### ISSUE TITLE
Case on https://github.com/sirupsen/logrus import

### ISSUE THREAD

**Issue by wcarmon** [adlio/trello#1]
It looks like you are using lower case instead of upper case for the import.

This causes compiler errors that look like:
case-insensitive import collision: "vendor/github.com/Sirupsen/logrus" and "vendor/github.com/sirupsen/logrus"

Their examples use upper case: https://github.com/sirupsen/logrus.
It looks like they reverted the brief change to lower case a while back: 

- https://github.com/containerd/containerd/pull/448/commits/727f0a536e3494b008c8f4d497d1b0746af16e73
- https://github.com/containerd/containerd/pull/448

**Comment by adlio** [comment]
Erggg... that change was right between the switch from Upper to lower and back to upper as I was building this library. I'm going to replace logrus with an interface to allow optionally plugging in a debug logger, since we're exclusively using logrus for Debugf statements at this point.

**Comment by wcarmon** [comment]
ok, I'm using vendoring so I just changed it locally.  
Hopefully this helps anyone that runs into the same issue.

Thanks for building a great library by the way!
