### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by fimdomeio** [adlio/trello#26]
I was playing around with your lib and found out I could not use custom fields (a trello Power Up). So I forked your repo and did a rough implementation.

Do you think it would be interesting for me to fine tune it and make a PR to adlio/trello or that power up functionality does not really belong here?

In any case thank you for sharing this lib.

**Comment by gesellix** [comment]
see #21

**Comment by adlio** [comment]
As @gesellix mentions, there is support in PR #21, which I just merged.
