### ISSUE TITLE
Checklst API

### ISSUE THREAD

**Issue by madetara** [adlio/trello#37]
Hello!

Your package is great overall, but I noticed that it lacks API methods to work with checklists. It happened so that I need some of them, so I'd like to work on it.

It might take some time, so feel free to contact me for collaboration :)

**Comment by adlio** [comment]
Agreed! It may take me some time to do it myself. I'm very welcoming of PRs for feature additions if you've got some time.

Thanks for the feedback.

**Comment by adlio** [comment]
Thanks to @fabstu, basic checklist creation is now supported.
