### ISSUE TITLE
Couldn't fetch custom fields values when getting a list of cards

### ISSUE THREAD

**Issue by AlmogBaku** [adlio/trello#42]
Probably due to an API change, but the current implementation doesn't fetch the custom field value(when requested in the query param).
The problem caused by missing fields in the `CustomFieldItem` struct.

@mangelajo @adlio

**Comment by adlio** [comment]
Re-opening this issue. I'm interested in ways to fetch custom values more comprehensively.

**Comment by AlmogBaku** [comment]
@adlio I fixed the bug occurred in my previous PR
