### ISSUE TITLE
Attachments[] is always empty even if there is attachments

### ISSUE THREAD

**Issue by Trini8ed** [adlio/trello#87]
Using the latest release v1.9.0, hopefully I'm just doing something wrong but I have a giant list of cards all with attachments and after doing GetCards() from a list it seems the attachments array in all of them are empty. Is there possibly something I'm missing here I know all the cards have attachments and the rest of the array data is there not sure what else to try here.

**Comment by xaxulin** [comment]
Use "Add method to get all card attachments #81" from https://github.com/adlio/trello/pull/81

**Comment by Trini8ed** [comment]
Needed to make sure I was not using trell.defaults not sure how I missed this earlier.
